## Neural Network Introduction #2

This exercise is adapted from https://www.springboard.com/blog/beginners-guide-neural-network-in-python-scikit-learn-0-18/

Now you have successfully used SciKit Learn's MLP to work on the built-in Breast Cancer Data Set, let's try another one!

Download the wine dataset from UCI Machine learning repository (http://archive.ics.uci.edu/ml/datasets/Wine/). Import the dataset into a pandas dataframe

In [1]:
import pandas as pd
import numpy as np
wine = pd.read_csv("Data/Wine.csv")

Check out the dataframe - what are the first few rows of data?

In [2]:
# find out the attributes in the dataset
wine.head(10)

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   
5    14.20        1.76  2.45          15.2        112           3.27   
6    14.39        1.87  2.45          14.6         96           2.50   
7    14.06        2.15  2.61          17.6        121           2.60   
8    14.83        1.64  2.17          14.0         97           2.80   
9    13.86        1.35  2.27          16.0         98           2.98   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   
5        3.39                  0.34             1.97             6.75  1.05   
6        2.52                  0.30             1.98             5.25  1.02   
7        2.51                  0.31             1.25             5.05  1.06   
8        2.98                  0.29             1.98             5.20  1.08   
9        3.15                  0.22             1.85             7.22  1.01   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1  
5   2.85     1450                 1  
6   3.58     1290                 1  
7   3.58     1295                 1  
8   2.85     1045                 1  
9   3.55     1045                 1

In [3]:
# find out the total instances and number of features
wine.shape

(178, 14)

In [4]:
# use describe to find out more about the data
wine.describe()

Alcohol  Malic_Acid         Ash  Ash_Alcanity   Magnesium  \
count  178.000000  178.000000  178.000000    178.000000  178.000000   
mean    13.000618    2.336348    2.366517     19.494944   99.741573   
std      0.811827    1.117146    0.274344      3.339564   14.282484   
min     11.030000    0.740000    1.360000     10.600000   70.000000   
25%     12.362500    1.602500    2.210000     17.200000   88.000000   
50%     13.050000    1.865000    2.360000     19.500000   98.000000   
75%     13.677500    3.082500    2.557500     21.500000  107.000000   
max     14.830000    5.800000    3.230000     30.000000  162.000000   

       Total_Phenols  Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       Color_Intensity         Hue       OD280      Proline  Customer_Segment  
count       178.000000  178.000000  178.000000   178.000000        178.000000  
mean          5.058090    0.957449    2.611685   746.893258          1.938202  
std           2.318286    0.228572    0.709990   314.907474          0.775035  
min           1.280000    0.480000    1.270000   278.000000          1.000000  
25%           3.220000    0.782500    1.937500   500.500000          1.000000  
50%           4.690000    0.965000    2.780000   673.500000          2.000000  
75%           6.200000    1.120000    3.170000   985.000000          3.000000  
max          13.000000    1.710000    4.000000  1680.000000          3.000000

**Q:** what can you say about this dataset?

Now, set up the data (x) and labels (y)


In [5]:
#assign target column to Y - pop remove the whole column from the dataframe
Y=wine.pop('Customer_Segment')

In [6]:
#assign all the remaining columns into X variable and assign as float data type
X = wine.astype(float)
X

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6      127.0           2.80   
1      13.20        1.78  2.14          11.2      100.0           2.65   
2      13.16        2.36  2.67          18.6      101.0           2.80   
3      14.37        1.95  2.50          16.8      113.0           3.85   
4      13.24        2.59  2.87          21.0      118.0           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5       95.0           1.68   
174    13.40        3.91  2.48          23.0      102.0           1.80   
175    13.27        4.28  2.26          20.0      120.0           1.59   
176    13.17        2.59  2.37          20.0      120.0           1.65   
177    14.13        4.10  2.74          24.5       96.0           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  
0     3.92   1065.0  
1     3.40   1050.0  
2     3.17   1185.0  
3     3.45   1480.0  
4     2.93    735.0  
..     ...      ...  
173   1.74    740.0  
174   1.56    750.0  
175   1.56    835.0  
176   1.62    840.0  
177   1.60    560.0  

[178 rows x 13 columns]

In [7]:
Y.value_counts()

2    71
1    59
3    48
Name: Customer_Segment, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
# encode class values
encoder = LabelEncoder()
encoder.fit(Y)
y = encoder.transform(Y)

#### Train Test Split
 
Let's split our data into training and testing sets, this is done easily with SciKit Learn's train_test_split function from model_selection:

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

#### Data Preprocessing
 
The neural network may have difficulty converging before the maximum number of iterations allowed if the data is not normalized. Multi-layer Perceptron is sensitive to feature scaling, so it is highly recommended to scale your data. Note that you must apply the same scaling to the test set for meaningful results. There are a lot of different methods for normalization of data, we will use the built-in StandardScaler for standardization.

In [11]:
# Import the StandardScalar library
from sklearn.preprocessing import StandardScaler

# Fit only to the training data
scaler = StandardScaler()

In [12]:
# Now apply the transformations to the data:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#### Training the model
 
Now it is time to train our model. SciKit Learn makes this incredibly easy, by using estimator objects. In this case we will import our estimator (the Multi-Layer Perceptron Classifier model) from the neural_network library of SciKit-Learn!

In [13]:
from sklearn.neural_network import MLPClassifier

Next we create an instance of the model, there are a lot of parameters you can choose to define and customize here, we will only define the hidden_layer_sizes. For this parameter you pass in a tuple consisting of the number of neurons you want at each layer, where the nth entry in the tuple represents the number of neurons in the nth layer of the MLP model. There are many ways to choose these numbers, but for simplicity we will choose 3 layers with the same number of neurons as there are features in our data set:

In [14]:
# create a Multilayerperceptron classifier and call it mlp
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)

Now that the model has been made we can fit the training data to our model, remember that this data has already been processed and scaled:

In [15]:
mlp.fit(X_train,y_train)

MLPClassifier(hidden_layer_sizes=(13, 13, 13), max_iter=500)

**Q:** What do you see in the output? What does it tell you?

#### Predictions and Evaluation
 
Now that we have a model it is time to use it to get predictions! We can do this simply with the predict() method off of our fitted model:

In [16]:
y_pred = mlp.predict(X_test)
y_pred

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0, 2, 2, 1, 2, 1, 1, 1, 1,
       2], dtype=int64)

Now we can use SciKit-Learn's built in metrics such as a classification report and confusion matrix to evaluate how well our model performed:

In [17]:
from sklearn.metrics import classification_report, confusion_matrix

In [18]:
print("Confusion Matrix: \n" , confusion_matrix(y_test, y_pred))
print("Classification Report: \n" , classification_report(y_test, y_pred))

Confusion Matrix: 
 [[14  1  0]
 [ 0 18  0]
 [ 0  0 12]]
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      0.93      0.97        15
           1       0.95      1.00      0.97        18
           2       1.00      1.00      1.00        12

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



**Q:** what conclusion can you make from the confusion matrix?

#### Weights and biases

The downside however to using a Multi-Layer Preceptron model is how difficult it is to interpret the model itself. The weights and biases won't be easily interpretable in relation to which features are important to the model itself.

To extract the MLP weights and biases after training your model, you use its public attributes coefs_ and intercepts_.

In [19]:
# Print the coefficient values and interpret it
len(mlp.coefs_)

4

In [20]:
# Print the intercepts values and interpret it
len(mlp.intercepts_[0])

13

**Q:** What do you understand from the two values?

#### Additional optional tasks...

select a few known supervised techniques and compare their performance. Use 10 fold cross validation

### Naive Bayes

In [21]:
#Import libraries
from sklearn.naive_bayes import GaussianNB
from sklearn import model_selection
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score
from numpy import mean

#Experimental setup
seed = 7
kfold = model_selection.KFold(n_splits=10, random_state=seed, shuffle=True)

#Define the model
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [22]:
# evaluate the model choose mean as the result
results = model_selection.cross_val_score(model, X, y, cv=kfold)
print(results.mean())

0.977124183006536


In [23]:
y_pred_nb = model.predict(X_test)

In [24]:
print("Confusion Matrix: \n" , confusion_matrix(y_test, y_pred_nb))
print("Classification Report: \n" , classification_report(y_test, y_pred_nb))

Confusion Matrix: 
 [[15  0  0]
 [ 0 18  0]
 [ 0  0 12]]
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        12

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



### Decision Tree

In [25]:
from sklearn.tree import DecisionTreeClassifier

#Make an instance of the Model
clf = DecisionTreeClassifier(max_depth=2)

#Train the model on the data
clf.fit(X_train, y_train)

# evaluate the model choose mean as the result
cv_score = cross_val_score(clf, X_train, y_train, cv=10)
print (cv_score.mean())

0.8785714285714287


In [26]:
#Predict labels of unseen (test) data
y_pred_dt = clf.predict(X_test)

In [27]:
print("Confusion Matrix: \n" , confusion_matrix(y_test, y_pred_dt))
print("Classification Report: \n" , classification_report(y_test, y_pred_dt))

Confusion Matrix: 
 [[13  2  0]
 [ 4 14  0]
 [ 1  0 11]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.72      0.87      0.79        15
           1       0.88      0.78      0.82        18
           2       1.00      0.92      0.96        12

    accuracy                           0.84        45
   macro avg       0.87      0.85      0.86        45
weighted avg       0.86      0.84      0.85        45

